name: Build Project
on:
  push:
    branches:
    - ci

jobs:
  Build_for_Platforms:
    name: Build_for_${{ matrix.targetPlatform }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix: 
        targetPlatform:
          - StandaloneWindows 
          - StandaloneLinux64 
    steps: 
      - uses: actions/checkout@v2
        with:  
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}               

      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}